
import java.awt.*;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicProgressBarUI;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Francisco Manuel Perez Sanchez
 *
 */
public class Interfaz extends javax.swing.JFrame {
    
    //Creamos los 10 procesos que vamos utlizar
    public static Proceso hilo1;
    public static Proceso hilo2;
    public static Proceso hilo3;
    public static Proceso hilo4;
    public static Proceso hilo5;
    public static Proceso hilo6;
    public static Proceso hilo7;
    public static Proceso hilo8;
    public static Proceso hilo9;
    public static Proceso hilo10;
    
    public Interfaz() {
        initComponents();
        //Asignamos el nombre de cada hilo y su respectiva barra;
        Interfaz.hilo1= new Proceso("Proceso 1",barraHilo1);
        Interfaz.hilo2= new Proceso("Proceso 2",barraHilo2);
        Interfaz.hilo3 = new Proceso("Proceso 3",barraHilo3);
        Interfaz.hilo4 = new Proceso("Proceso 4",barraHilo4);
        Interfaz.hilo5 = new Proceso("Proceso 5",barraHilo5);
        Interfaz.hilo6 = new Proceso("Proceso 6",barraHilo6);
        Interfaz.hilo7 = new Proceso("Proceso 7",barraHilo7);
        Interfaz.hilo8 = new Proceso("Proceso 8",barraHilo8);
        Interfaz.hilo9 = new Proceso("Proceso 9",barraHilo9);
        Interfaz.hilo10 = new Proceso("Proceso 10",barraHilo10);
        this.setLocationRelativeTo(null); //Ventana aparezca en el centro
        
//Cada indicador de entrada y salida en un principio se deben ocultar con los sigueintes intrucciones
        segunda.setVisible(false);
        primer1.setVisible(false);
        segunda2.setVisible(false);
        primer2.setVisible(false);
        segunda3.setVisible(false);
        primer3.setVisible(false);
        segunda4.setVisible(false);
        primer4.setVisible(false);
        segunda5.setVisible(false);
        primer5.setVisible(false);
        segunda6.setVisible(false);
        primer6.setVisible(false);
        segunda7.setVisible(false);
        primer7.setVisible(false);
        segunda8.setVisible(false);
        primer8.setVisible(false);
        segunda9.setVisible(false);
        primer9.setVisible(false);
        segunda10.setVisible(false);
        primer10.setVisible(false);
        
        //Mostramos en la ventana los datos de cada proceso 
       Etiqueta1.setText("<html>Tamaño: 25 <br> E/S: 5 <br> E/S: 15 </html> ");
       Etiqueta2.setText("<html>Tamaño: 35 <br> E/S: 10 <br> E/S: 30 </html> ");
       Etiqueta3.setText("<html>Tamaño: 30 <br> E/S: 15 <br> E/S: 25 </html> ");
       Etiqueta4.setText("<html>Tamaño: 20 <br> E/S: 5 <br> E/S: 15 </html> ");
       Etiqueta5.setText("<html>Tamaño: 40 <br> E/S: 20 <br> E/S: 35 </html> ");
       Etiqueta6.setText("<html>Tamaño: 35 <br> E/S: 15 <br> E/S: 30 </html> ");
       Etiqueta7.setText("<html>Tamaño: 50 <br> E/S: 15 <br> E/S: 35 </html> ");
       Etiqueta8.setText("<html>Tamaño: 35 <br> E/S: 5 <br> E/S: 25 </html> ");
       Etiqueta9.setText("<html>Tamaño: 45 <br> E/S: 15 <br> E/S: 40 </html> ");
       Etiqueta10.setText("<html>Tamaño: 30 <br> E/S: 10 <br> E/S: 20 </html> ");
       

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        segunda10 = new javax.swing.JLabel();
        segunda9 = new javax.swing.JLabel();
        segunda8 = new javax.swing.JLabel();
        segunda7 = new javax.swing.JLabel();
        segunda6 = new javax.swing.JLabel();
        segunda5 = new javax.swing.JLabel();
        segunda4 = new javax.swing.JLabel();
        segunda3 = new javax.swing.JLabel();
        segunda2 = new javax.swing.JLabel();
        segunda = new javax.swing.JLabel();
        primer10 = new javax.swing.JLabel();
        primer9 = new javax.swing.JLabel();
        primer8 = new javax.swing.JLabel();
        primer7 = new javax.swing.JLabel();
        primer6 = new javax.swing.JLabel();
        primer5 = new javax.swing.JLabel();
        primer4 = new javax.swing.JLabel();
        primer3 = new javax.swing.JLabel();
        primer2 = new javax.swing.JLabel();
        primer1 = new javax.swing.JLabel();
        barraHilo1 = new javax.swing.JProgressBar();
        barraHilo2 = new javax.swing.JProgressBar();
        barraHilo3 = new javax.swing.JProgressBar();
        barraHilo6 = new javax.swing.JProgressBar();
        barraHilo4 = new javax.swing.JProgressBar();
        barraHilo5 = new javax.swing.JProgressBar();
        barraHilo7 = new javax.swing.JProgressBar();
        barraHilo8 = new javax.swing.JProgressBar();
        barraHilo9 = new javax.swing.JProgressBar();
        barraHilo10 = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        Etiqueta1 = new javax.swing.JLabel();
        Etiqueta2 = new javax.swing.JLabel();
        Etiqueta3 = new javax.swing.JLabel();
        Etiqueta4 = new javax.swing.JLabel();
        Etiqueta5 = new javax.swing.JLabel();
        Etiqueta6 = new javax.swing.JLabel();
        Etiqueta7 = new javax.swing.JLabel();
        Etiqueta8 = new javax.swing.JLabel();
        Etiqueta9 = new javax.swing.JLabel();
        Etiqueta10 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Multiprogramacion");
        setIconImage(getIconImage());

        jScrollPane1.setAutoscrolls(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 900));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PROCESOS: ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(13, 11, 90, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Proceso 1 ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(13, 60, 70, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Proceso 2");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(13, 144, 70, 27);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Proceso 4 ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(13, 298, 70, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Proceso 3");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(13, 221, 60, 27);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Proceso 5 ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(13, 375, 70, 27);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Proceso 7 ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(13, 529, 60, 27);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Proceso 6 ");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(13, 452, 70, 27);
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 760, 0, 27);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Proceso 8 ");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(13, 606, 60, 27);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Proceso 9 ");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(13, 683, 70, 27);

        segunda10.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda10.setForeground(new java.awt.Color(204, 0, 0));
        segunda10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda10.setText("|");
        segunda10.setToolTipText("20% Segunda E/S");
        segunda10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda10);
        segunda10.setBounds(230, 753, 9, 35);

        segunda9.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda9.setForeground(new java.awt.Color(204, 0, 0));
        segunda9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda9.setText("|");
        segunda9.setToolTipText("40% Segunda E/S");
        segunda9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda9);
        segunda9.setBounds(396, 676, 9, 35);

        segunda8.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda8.setForeground(new java.awt.Color(204, 0, 0));
        segunda8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda8.setText("|");
        segunda8.setToolTipText("25% Segunda E/S");
        segunda8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda8);
        segunda8.setBounds(274, 599, 9, 35);

        segunda7.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda7.setForeground(new java.awt.Color(204, 0, 0));
        segunda7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda7.setText("|");
        segunda7.setToolTipText("35% Segunda E/S");
        segunda7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda7);
        segunda7.setBounds(356, 522, 9, 35);

        segunda6.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda6.setForeground(new java.awt.Color(204, 0, 0));
        segunda6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda6.setText("|");
        segunda6.setToolTipText("30% Segunda E/S");
        segunda6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda6);
        segunda6.setBounds(316, 445, 9, 35);

        segunda5.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda5.setForeground(new java.awt.Color(204, 0, 0));
        segunda5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda5.setText("|");
        segunda5.setToolTipText("35% Segunda E/S");
        segunda5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda5);
        segunda5.setBounds(358, 368, 9, 35);

        segunda4.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda4.setForeground(new java.awt.Color(204, 0, 0));
        segunda4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda4.setText("|");
        segunda4.setToolTipText("15% Segunda E/S");
        segunda4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda4);
        segunda4.setBounds(196, 291, 9, 35);

        segunda3.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda3.setForeground(new java.awt.Color(204, 0, 0));
        segunda3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda3.setText("|");
        segunda3.setToolTipText("25% Segunda E/S");
        segunda3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda3);
        segunda3.setBounds(274, 214, 9, 35);

        segunda2.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda2.setForeground(new java.awt.Color(204, 0, 0));
        segunda2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda2.setText("|");
        segunda2.setToolTipText("30% Segunda E/S");
        segunda2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda2);
        segunda2.setBounds(316, 137, 9, 35);

        segunda.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        segunda.setForeground(new java.awt.Color(204, 0, 0));
        segunda.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        segunda.setText("|");
        segunda.setToolTipText("15% Segunda E/S");
        segunda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(segunda);
        segunda.setBounds(196, 54, 9, 35);

        primer10.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer10.setForeground(new java.awt.Color(204, 0, 0));
        primer10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer10.setText("|");
        primer10.setToolTipText("10% Primera E/S");
        primer10.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer10);
        primer10.setBounds(150, 753, 9, 35);

        primer9.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer9.setForeground(new java.awt.Color(204, 0, 0));
        primer9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer9.setText("|");
        primer9.setToolTipText("15% Primera E/S");
        primer9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer9);
        primer9.setBounds(196, 676, 9, 35);

        primer8.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer8.setForeground(new java.awt.Color(204, 0, 0));
        primer8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer8.setText("|");
        primer8.setToolTipText("5% Primera E/S");
        primer8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer8);
        primer8.setBounds(118, 599, 9, 35);

        primer7.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer7.setForeground(new java.awt.Color(204, 0, 0));
        primer7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer7.setText("|");
        primer7.setToolTipText("15% Primera E/S");
        primer7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer7);
        primer7.setBounds(196, 522, 9, 35);

        primer6.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer6.setForeground(new java.awt.Color(204, 0, 0));
        primer6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer6.setText("|");
        primer6.setToolTipText("15% Primera E/S");
        primer6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer6);
        primer6.setBounds(196, 445, 9, 35);

        primer5.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer5.setForeground(new java.awt.Color(204, 0, 0));
        primer5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer5.setText("|");
        primer5.setToolTipText("20% Primera E/S");
        primer5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer5);
        primer5.setBounds(238, 368, 9, 35);

        primer4.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer4.setForeground(new java.awt.Color(204, 0, 0));
        primer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer4.setText("|");
        primer4.setToolTipText("5% Primera E/S");
        primer4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer4);
        primer4.setBounds(118, 291, 9, 35);

        primer3.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer3.setForeground(new java.awt.Color(204, 0, 0));
        primer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer3.setText("|");
        primer3.setToolTipText("15% Primera E/S");
        primer3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer3);
        primer3.setBounds(196, 214, 9, 35);

        primer2.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer2.setForeground(new java.awt.Color(204, 0, 0));
        primer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer2.setText("|");
        primer2.setToolTipText("10% Primera E/S");
        primer2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer2);
        primer2.setBounds(154, 137, 9, 35);

        primer1.setFont(new java.awt.Font("Impact", 1, 28)); // NOI18N
        primer1.setForeground(new java.awt.Color(204, 0, 0));
        primer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        primer1.setText("|");
        primer1.setToolTipText("5% Primera E/S");
        primer1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(primer1);
        primer1.setBounds(116, 54, 9, 35);

        barraHilo1.setToolTipText("Progreso 1");
        barraHilo1.setName(""); // NOI18N
        barraHilo1.setStringPainted(true);
        jPanel1.add(barraHilo1);
        barraHilo1.setBounds(81, 61, 800, 27);

        barraHilo2.setToolTipText("Progreso 2");
        barraHilo2.setStringPainted(true);
        jPanel1.add(barraHilo2);
        barraHilo2.setBounds(81, 144, 800, 27);

        barraHilo3.setToolTipText("Progreso 3");
        barraHilo3.setStringPainted(true);
        jPanel1.add(barraHilo3);
        barraHilo3.setBounds(81, 221, 800, 27);

        barraHilo6.setToolTipText("Progreso 6");
        barraHilo6.setStringPainted(true);
        jPanel1.add(barraHilo6);
        barraHilo6.setBounds(81, 452, 800, 27);

        barraHilo4.setToolTipText("Progreso 4");
        barraHilo4.setStringPainted(true);
        jPanel1.add(barraHilo4);
        barraHilo4.setBounds(81, 298, 800, 27);

        barraHilo5.setToolTipText("Progreso 5");
        barraHilo5.setStringPainted(true);
        jPanel1.add(barraHilo5);
        barraHilo5.setBounds(81, 375, 800, 27);

        barraHilo7.setToolTipText("Progreso 7");
        barraHilo7.setStringPainted(true);
        jPanel1.add(barraHilo7);
        barraHilo7.setBounds(81, 529, 800, 27);

        barraHilo8.setToolTipText("Progreso 8");
        barraHilo8.setStringPainted(true);
        jPanel1.add(barraHilo8);
        barraHilo8.setBounds(81, 606, 800, 27);

        barraHilo9.setToolTipText("Progreso 9");
        barraHilo9.setStringPainted(true);
        jPanel1.add(barraHilo9);
        barraHilo9.setBounds(82, 683, 800, 27);

        barraHilo10.setToolTipText("Progreso 10");
        barraHilo10.setStringPainted(true);
        jPanel1.add(barraHilo10);
        barraHilo10.setBounds(76, 760, 800, 27);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Proceso 10 ");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 760, 70, 27);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BCh.png"))); // NOI18N
        jButton1.setText("INICIAR");
        jButton1.setContentAreaFilled(false);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/BCh.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/BGr.png"))); // NOI18N
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1085, 775, 105, 136);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CasaCh.png"))); // NOI18N
        jButton2.setText("INICIO");
        jButton2.setContentAreaFilled(false);
        jButton2.setDisabledIcon(null);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setName(""); // NOI18N
        jButton2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/CasaCh.png"))); // NOI18N
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CasaG.png"))); // NOI18N
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(995, 775, 105, 142);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Tamaño: 40");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(140, 348, 80, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Tamaño: 25");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(140, 34, 80, 20);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Tamaño: 30");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(140, 734, 80, 20);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Tamaño: 30");
        jPanel1.add(jLabel16);
        jLabel16.setBounds(140, 194, 80, 20);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Tamaño: 20");
        jPanel1.add(jLabel17);
        jLabel17.setBounds(140, 272, 80, 20);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Tamaño: 35");
        jPanel1.add(jLabel18);
        jLabel18.setBounds(140, 116, 80, 20);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Tamaño: 35");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(140, 426, 80, 20);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Tamaño: 50");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(140, 504, 80, 20);

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Tamaño: 35");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(140, 580, 80, 20);

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Tamaño: 45");
        jPanel1.add(jLabel22);
        jLabel22.setBounds(140, 658, 80, 20);

        Etiqueta1.setToolTipText("");
        Etiqueta1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta1);
        Etiqueta1.setBounds(920, 50, 250, 55);

        Etiqueta2.setBackground(new java.awt.Color(255, 255, 255));
        Etiqueta2.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Etiqueta2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(Etiqueta2);
        Etiqueta2.setBounds(920, 130, 250, 55);

        Etiqueta3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta3);
        Etiqueta3.setBounds(920, 210, 250, 55);

        Etiqueta4.setToolTipText("");
        Etiqueta4.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta4);
        Etiqueta4.setBounds(920, 280, 250, 55);

        Etiqueta5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta5);
        Etiqueta5.setBounds(920, 360, 250, 55);

        Etiqueta6.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta6);
        Etiqueta6.setBounds(920, 440, 250, 55);

        Etiqueta7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta7);
        Etiqueta7.setBounds(920, 520, 250, 55);

        Etiqueta8.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta8);
        Etiqueta8.setBounds(920, 590, 250, 55);

        Etiqueta9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta9);
        Etiqueta9.setBounds(920, 670, 250, 55);

        Etiqueta10.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(Etiqueta10);
        Etiqueta10.setBounds(920, 740, 250, 55);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("CAMBIOS");
        jPanel1.add(jLabel23);
        jLabel23.setBounds(990, 20, 60, 20);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Portada b=new Portada();// crreamos un objeto de la portada
        b.setVisible(true); // hacemos visible esta ventana
        this.setVisible(false); // y ocultamos la ventana de las barras
    }//GEN-LAST:event_jButton2ActionPerformed

    //Metodo del boton iniciar
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Asignamos los tamaños de cada proceso
        hilo1.iniciar(25);
        hilo2.iniciar(35);
        hilo3.iniciar(30);
        hilo4.iniciar(20);
        hilo5.iniciar(40);
        hilo6.iniciar(35);
        hilo7.iniciar(50);
        hilo8.iniciar(35);
        hilo9.iniciar(45);
        hilo10.iniciar(30);
        hilo1.start(); //iniciamos el primer hilo de la clase Proceso
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    @Override
    public Image getIconImage(){
//        Para cambiar el incono de la ventana de multiprogramacion
        Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("ALU.png"));
        return retValue;
    }
    
    
   
    public static void main(String args[]) {
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Interfaz ventana= new Interfaz();
                ventana.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel Etiqueta1;
    public static javax.swing.JLabel Etiqueta10;
    public static javax.swing.JLabel Etiqueta2;
    public static javax.swing.JLabel Etiqueta3;
    public static javax.swing.JLabel Etiqueta4;
    public static javax.swing.JLabel Etiqueta5;
    public static javax.swing.JLabel Etiqueta6;
    public static javax.swing.JLabel Etiqueta7;
    public static javax.swing.JLabel Etiqueta8;
    public static javax.swing.JLabel Etiqueta9;
    private javax.swing.JProgressBar barraHilo1;
    private javax.swing.JProgressBar barraHilo10;
    private javax.swing.JProgressBar barraHilo2;
    private javax.swing.JProgressBar barraHilo3;
    private javax.swing.JProgressBar barraHilo4;
    private javax.swing.JProgressBar barraHilo5;
    private javax.swing.JProgressBar barraHilo6;
    private javax.swing.JProgressBar barraHilo7;
    private javax.swing.JProgressBar barraHilo8;
    private javax.swing.JProgressBar barraHilo9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel primer1;
    public static javax.swing.JLabel primer10;
    public static javax.swing.JLabel primer2;
    public static javax.swing.JLabel primer3;
    public static javax.swing.JLabel primer4;
    public static javax.swing.JLabel primer5;
    public static javax.swing.JLabel primer6;
    public static javax.swing.JLabel primer7;
    public static javax.swing.JLabel primer8;
    public static javax.swing.JLabel primer9;
    public static javax.swing.JLabel segunda;
    public static javax.swing.JLabel segunda10;
    public static javax.swing.JLabel segunda2;
    public static javax.swing.JLabel segunda3;
    public static javax.swing.JLabel segunda4;
    public static javax.swing.JLabel segunda5;
    public static javax.swing.JLabel segunda6;
    public static javax.swing.JLabel segunda7;
    public static javax.swing.JLabel segunda8;
    public static javax.swing.JLabel segunda9;
    // End of variables declaration//GEN-END:variables
}
