
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pfran
 */
public class Portada extends javax.swing.JFrame {
    
    /**
     * Creates new form Portada
     */
    public Portada() {
        initComponents();
        this.setLocationRelativeTo(null);
         
        

    }
    
    @Override
    public Image getIconImage(){
        //Imagenes que nos ayuda a la presentacion de nuestr
        Image retValue= Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Itp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        boton1 = new javax.swing.JButton();
        cerrar = new javax.swing.JButton();
        minimizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Arquitectura de Computadoras");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName(""); // NOI18N
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1020, 750));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1020, 750));
        jPanel1.setLayout(null);

        boton1.setFont(new java.awt.Font("Baskerville Old Face", 0, 14)); // NOI18N
        boton1.setForeground(new java.awt.Color(204, 204, 204));
        boton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chico.png"))); // NOI18N
        boton1.setText("INICIAR");
        boton1.setToolTipText("INICIAR");
        boton1.setContentAreaFilled(false);
        boton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/chico.png"))); // NOI18N
        boton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Grande.png"))); // NOI18N
        boton1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        boton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        jPanel1.add(boton1);
        boton1.setBounds(400, 620, 105, 120);

        cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/browser-5_90955 (1).png"))); // NOI18N
        cerrar.setToolTipText("CERRAR");
        cerrar.setContentAreaFilled(false);
        cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(cerrar);
        cerrar.setBounds(979, 0, 38, 36);
        cerrar.getAccessibleContext().setAccessibleName("Cerrar");

        minimizar.setBackground(new java.awt.Color(0, 0, 0));
        minimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/shrink_90996 (1).png"))); // NOI18N
        minimizar.setToolTipText("MINIMIZAR");
        minimizar.setContentAreaFilled(false);
        minimizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizarActionPerformed(evt);
            }
        });
        jPanel1.add(minimizar);
        minimizar.setBounds(950, 0, 39, 36);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ephy.gif"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 560, 510, 289);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ephy.gif"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 500, 281);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ephy.gif"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(500, 0, 511, 281);

        jLabel6.setBackground(new java.awt.Color(51, 51, 255));
        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Arquitectura de computadoras");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(600, 540, 310, 43);

        jLabel7.setBackground(new java.awt.Color(51, 51, 255));
        jLabel7.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 204));
        jLabel7.setText("TECNOLÓGICO NACIONAL DE MÉXICO");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(530, 470, 490, 47);

        jLabel8.setBackground(new java.awt.Color(51, 51, 255));
        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 153, 0));
        jLabel8.setText("INSTITUTO TECNOLÓGICO DE PUEBLA");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(530, 510, 490, 43);

        jLabel9.setBackground(new java.awt.Color(51, 51, 255));
        jLabel9.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 204));
        jLabel9.setText("Perez Sanchez Francisco Manuel");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(670, 620, 350, 43);

        jLabel10.setBackground(new java.awt.Color(51, 51, 255));
        jLabel10.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Multiprogramación");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(650, 580, 200, 43);

        jLabel11.setBackground(new java.awt.Color(51, 51, 255));
        jLabel11.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Integrantes:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(520, 620, 140, 43);

        jLabel12.setBackground(new java.awt.Color(51, 51, 255));
        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Sepulveda Flores Xcaret");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(670, 650, 330, 43);

        jLabel13.setBackground(new java.awt.Color(51, 51, 255));
        jLabel13.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 204));
        jLabel13.setText("Trejo Valerdi Carmina Monserrat");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(670, 685, 360, 43);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ephy.gif"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, 284, 510, 281);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ephy.gif"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(500, 284, 510, 190);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
        Interfaz a=new Interfaz();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_boton1ActionPerformed

    private void cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cerrarActionPerformed
        //cerrar aplicacion
        System.exit(0);
    }//GEN-LAST:event_cerrarActionPerformed

    private void minimizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizarActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_minimizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Portada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Portada().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton cerrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizar;
    // End of variables declaration//GEN-END:variables
}
